# goal
geometry_msgs/Pose pose
std_msgs/Bool do_x
std_msgs/Bool do_y
std_msgs/Bool do_z
std_msgs/Bool do_quaternion
std_msgs/Bool displace
std_msgs/Bool local
---
# result
std_msgs/Bool status
---
# feedback 
std_msgs/Bool status
