services:
  douglas:
    environment:
      - DISPLAY=novnc:0.0 
    volumes:
      - ../../../AUV-2025:/AUV-2025
    build:
      context: .
      dockerfile: base.dockerfile
    command: bash -c "tail -f /dev/null"
    ports:
      - "8765:8765"
      - "10000:10000"