services: 
  douglas:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ../../../AUV-2025
        target: /AUV-2025
    image: "mcgillrobotics/auv_2025:jetson" 
    privileged: true
    container_name: douglas_noetic
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - UDEV=on
      - ROS_MASTER_URI=http://douglas_noetic:11311
      - ROS_IP=douglas_noetic
    runtime: nvidia
    command: bash -c "source /opt/ros/noetic/setup.bash && roscore" 
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true

  zed:
    volumes:
      - /dev:/dev
    image: "mcgillrobotics/auv_2025:zed"
    build:
      context: ../../../AUV-2025
      dockerfile: Docker/jetson/Dockerfile.zed
    privileged: true
    container_name: zed_humble
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - UDEV=on
    runtime: nvidia
    command: bash -c "source /opt/ros/humble/setup.bash && source /root/ros2_ws/install/local_setup.bash && ros2 launch zed_wrapper zed_camera.launch.py camera_model:=zed2i" 
    network_mode: host 

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    
  bridge:
    image: "mcgillrobotics/auv_2025:rosbridge"
    container_name: bridge_bridge
    depends_on:
      - douglas
      - zed
    build:
      context: ../../../AUV-2025
      dockerfile: Docker/jetson/Dockerfile.bridge
    privileged: true
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - ROS_MASTER_URI=http://douglas_noetic:11311
      - ROS_IP=douglas_noetic
    tty: true
