FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y \
    curl \
    gnupg2 \
    lsb-release \
    software-properties-common \
    build-essential \
    cmake \
    python3-pip \
    git \
    wget

RUN pip3 install colcon-common-extensions

#Install ROS 2 Humble from binary 
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | \
    gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" \
    > /etc/apt/sources.list.d/ros2-latest.list && \
    apt-get update && \
    apt-get install -y ros-humble-ros-base && \
    echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc

# Install Python packages for ROS1 building via pip
RUN pip3 install --upgrade pip
RUN pip3 install rosdep catkin_pkg vcstool empy rosinstall-generator
ENV PATH="/root/.local/bin:$PATH"

RUN rosdep init && rosdep update

RUN mkdir -p /root/noetic_ws/src
WORKDIR /root/noetic_ws
RUN rosinstall_generator ros_comm --rosdistro noetic --deps --tar > noetic-ros_comm.rosinstall && \
    vcs import src < noetic-ros_comm.rosinstall

RUN apt-get update && \
    rosdep install --from-paths src --ignore-src -y --skip-keys "fastcdr rti-connext-dds-6.0.1 urdfdom_headers ignition-cmake2 ignition-math6 python3-catkin-pkg-modules python3-rosdistro-modules python3-vcstool" --rosdistro humble || true

RUN mkdir -p /root/catkin_ws/src && \
    cd /root/catkin_ws/src && \
    git clone -b noetic-devel https://github.com/ros/catkin.git

RUN pip3 install -e /root/catkin_ws/src/catkin

RUN cd /root/catkin_ws/src/catkin && \
    chmod +x bin/catkin_make_isolated && \
    cp bin/catkin_make_isolated /usr/local/bin/


# --- Patch rosconsole for log4cxx compatibility ---
RUN sed -i 's/logger->addAppender(new ROSConsoleStdioAppender);/logger->addAppender(log4cxx::AppenderPtr(new ROSConsoleStdioAppender));/g' /root/noetic_ws/src/rosconsole/src/rosconsole/impl/rosconsole_log4cxx.cpp && \
    sed -i 's/return log4cxx::Logger::getLogger(name);/return log4cxx::Logger::getLogger(name).get();/g' /root/noetic_ws/src/rosconsole/src/rosconsole/impl/rosconsole_log4cxx.cpp && \
    sed -i 's/logger->addAppender(g_log4cxx_appender);/logger->addAppender(log4cxx::AppenderPtr(g_log4cxx_appender));/g' /root/noetic_ws/src/rosconsole/src/rosconsole/impl/rosconsole_log4cxx.cpp && \
    sed -i 's/logger->removeAppender(g_log4cxx_appender);/logger->removeAppender(log4cxx::AppenderPtr(g_log4cxx_appender));/g' /root/noetic_ws/src/rosconsole/src/rosconsole/impl/rosconsole_log4cxx.cpp && \
    sed -i 's/->getLoggerRepository()/->getLoggerRepository().lock()/g' /root/noetic_ws/src/rosconsole/src/rosconsole/impl/rosconsole_log4cxx.cpp

#WE ARE HERE
RUN catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release

RUN mkdir -p /root/bridge_ws/src
WORKDIR /root/bridge_ws/src
RUN git clone -b humble https://github.com/ros2/ros1_bridge.git

WORKDIR /root/bridge_ws
RUN . /opt/ros/humble/setup.bash && \
    . /root/noetic_ws/install_isolated/setup.bash && \
    rosdep update && \
    rosdep install --from-paths src --ignore-src -y --skip-keys "fastcdr rti-connext-dds-6.0.1 urdfdom_headers ignition-cmake2 ignition-math6 python3-catkin-pkg-modules python3-rosdistro-modules python3-vcstool" --rosdistro humble && \
    colcon build --symlink-install --packages-select ros1_bridge

# --- 7. Set entrypoint to source all setups and run the dynamic bridge ---
RUN echo 'source /opt/ros/humble/setup.bash && \
    source /root/noetic_ws/install_isolated/setup.bash && \
    source /root/bridge_ws/install/local_setup.bash && \
    exec "$@"' > /ros_entrypoint.sh && chmod +x /ros_entrypoint.sh

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["ros2", "run", "ros1_bridge", "dynamic_bridge"]
