# goal
geometry_msgs/Wrench effort
std_msgs/Bool do_x
std_msgs/Bool do_y
std_msgs/Bool do_z
std_msgs/Bool do_roll
std_msgs/Bool do_pitch
std_msgs/Bool do_yaw
std_msgs/Bool is_global
---
# result
std_msgs/Bool stopped
---
# feedback 
std_msgs/Bool moving