# DVL ensemble output data.

# (PD6) Details' in the Navigator Technical Manual for more information.


float64 depth
float64 temperature
float64 salinity

float64 roll
float64 pitch
float64 heading

float64 north_displacement
float64 east_displacement
float64 upward_displacement
float64 range_to_bottom
float64 time_since_good

float64 north_velocity
float64 east_velocity
float64 upward_velocity
bool velocity_valid

