geometry_msgs/Vector3 position
geometry_msgs/Quaternion orientation
geometry_msgs/Vector3 velocity
geometry_msgs/Vector3 angular_velocity
geometry_msgs/Vector3 linear_acceleration
int32[] frequencies
uint32[] hydrophone_one_freqs
uint32[] hydrophone_two_freqs
uint32[] hydrophone_three_freqs
uint32[] hydrophone_four_freqs

int32 is_dvl_active
int32 is_depth_sensor_active
int32 is_imu_active
int32 is_hydrophones_active
