ekf_global:
  ros__parameters:
    frequency: 20.0
    sensor_timeout: 0.1
    two_d_mode: false

    transform_time_offset: 0.0
    transform_timeout: 0.0

    print_diagnostics: true
    debug: false

    world_frame: odom
    map_frame: map
    odom_frame: odom
    base_link_frame: auv

    publish_tf: true    # publishes the `odom` -> `auv` transform

    # Define TOPIC NAMES
    odom0: /odometry/local
    # Use TWIST to prevent odometric and map frame conflicts
    odom0_config:
    [
      false, false, false,
      false, false, false,
      true,  true,  true, 
      true,  true,  true,
      false, false, false
    ]
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 5
    odom0_nodelay: false
    odom0_twist_rejection_threshold: 5.0   # m/s & rad/s (reasonable sanity gate)
    odom0_pose_rejection_threshold: 5.0

    odom1: /zed2i/zed_node/odom
    odom1_config:
    [
      true, true, true,
      true, true, true,
      false, false, false,
      false, false, false,
      false, false, false
    ]
    odom1_relative: false
    odom1_queue_size: 5
    odom1_differential: false
    odom1_nodelay: false
    odom1_rejection_threshold: 5.0
    
    dynamic_process_noise_covariance: true