// Generated by gencpp from file auv_msgs/ThrusterIntensities.msg
// DO NOT EDIT!


#ifndef AUV_MSGS_MESSAGE_THRUSTERINTENSITIES_H
#define AUV_MSGS_MESSAGE_THRUSTERINTENSITIES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auv_msgs
{
template <class ContainerAllocator>
struct ThrusterIntensities_
{
  typedef ThrusterIntensities_<ContainerAllocator> Type;

  ThrusterIntensities_()
    : intensities()  {
      intensities.assign(0.0);
  }
  ThrusterIntensities_(const ContainerAllocator& _alloc)
    : intensities()  {
  (void)_alloc;
      intensities.assign(0.0);
  }



   typedef boost::array<double, 8>  _intensities_type;
  _intensities_type intensities;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SURGE_PORT)
  #undef SURGE_PORT
#endif
#if defined(_WIN32) && defined(SURGE_STAR)
  #undef SURGE_STAR
#endif
#if defined(_WIN32) && defined(SWAY_BOW)
  #undef SWAY_BOW
#endif
#if defined(_WIN32) && defined(SWAY_STERN)
  #undef SWAY_STERN
#endif
#if defined(_WIN32) && defined(HEAVE_BOW_PORT)
  #undef HEAVE_BOW_PORT
#endif
#if defined(_WIN32) && defined(HEAVE_BOW_STAR)
  #undef HEAVE_BOW_STAR
#endif
#if defined(_WIN32) && defined(HEAVE_STERN_STAR)
  #undef HEAVE_STERN_STAR
#endif
#if defined(_WIN32) && defined(HEAVE_STERN_PORT)
  #undef HEAVE_STERN_PORT
#endif

  enum {
    SURGE_PORT = 0u,
    SURGE_STAR = 1u,
    SWAY_BOW = 2u,
    SWAY_STERN = 3u,
    HEAVE_BOW_PORT = 4u,
    HEAVE_BOW_STAR = 5u,
    HEAVE_STERN_STAR = 6u,
    HEAVE_STERN_PORT = 7u,
  };


  typedef boost::shared_ptr< ::auv_msgs::ThrusterIntensities_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auv_msgs::ThrusterIntensities_<ContainerAllocator> const> ConstPtr;

}; // struct ThrusterIntensities_

typedef ::auv_msgs::ThrusterIntensities_<std::allocator<void> > ThrusterIntensities;

typedef boost::shared_ptr< ::auv_msgs::ThrusterIntensities > ThrusterIntensitiesPtr;
typedef boost::shared_ptr< ::auv_msgs::ThrusterIntensities const> ThrusterIntensitiesConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auv_msgs::ThrusterIntensities_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auv_msgs::ThrusterIntensities_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::auv_msgs::ThrusterIntensities_<ContainerAllocator1> & lhs, const ::auv_msgs::ThrusterIntensities_<ContainerAllocator2> & rhs)
{
  return lhs.intensities == rhs.intensities;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::auv_msgs::ThrusterIntensities_<ContainerAllocator1> & lhs, const ::auv_msgs::ThrusterIntensities_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace auv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::auv_msgs::ThrusterIntensities_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_msgs::ThrusterIntensities_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auv_msgs::ThrusterIntensities_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auv_msgs::ThrusterIntensities_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_msgs::ThrusterIntensities_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_msgs::ThrusterIntensities_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auv_msgs::ThrusterIntensities_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87596f476e6e6d11faa2d0b54de1e74e";
  }

  static const char* value(const ::auv_msgs::ThrusterIntensities_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87596f476e6e6d11ULL;
  static const uint64_t static_value2 = 0xfaa2d0b54de1e74eULL;
};

template<class ContainerAllocator>
struct DataType< ::auv_msgs::ThrusterIntensities_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auv_msgs/ThrusterIntensities";
  }

  static const char* value(const ::auv_msgs::ThrusterIntensities_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auv_msgs::ThrusterIntensities_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Thruster definitions\n"
"uint8 SURGE_PORT=0\n"
"uint8 SURGE_STAR=1\n"
"uint8 SWAY_BOW=2\n"
"uint8 SWAY_STERN=3\n"
"uint8 HEAVE_BOW_PORT=4\n"
"uint8 HEAVE_BOW_STAR=5\n"
"uint8 HEAVE_STERN_STAR=6\n"
"uint8 HEAVE_STERN_PORT=7\n"
"\n"
"# -1 full backwards, 1 full forwards, 0 stop\n"
"float64[8] intensities\n"
;
  }

  static const char* value(const ::auv_msgs::ThrusterIntensities_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auv_msgs::ThrusterIntensities_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.intensities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThrusterIntensities_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auv_msgs::ThrusterIntensities_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auv_msgs::ThrusterIntensities_<ContainerAllocator>& v)
  {
    s << indent << "intensities[]" << std::endl;
    for (size_t i = 0; i < v.intensities.size(); ++i)
    {
      s << indent << "  intensities[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.intensities[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUV_MSGS_MESSAGE_THRUSTERINTENSITIES_H
