name: Docker Build & Push for base and dependencies

on:
  push:
    branches: [noetic]
  pull_request:
    branches: [noetic]
    paths:
      - 'Docker/base/**'
      - 'Docker/sim/**'
      - 'Docker/poolside/**'
      - '.github/workflows/docker_build_base.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-push-base-amd64:
    name: base-amd64-temp Docker image
    runs-on: ubuntu-22.04

    steps:
      - name: Free Disk Space
        uses: netbrain/free-disk-space-action@v0.0.1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (only if pushing)
        if: github.event_name == 'push' && github.ref == 'refs/heads/noetic'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and optionally push image
        uses: docker/build-push-action@v5
        with:
          context: Docker/base
          file: Docker/base/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/noetic' }}
          tags: mcgillrobotics/auv_2025:base-amd64-temp

  build-and-push-base-arm64:
    name: base-arm64-temp Docker image
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Free Disk Space
        uses: netbrain/free-disk-space-action@v0.0.1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (only if pushing)
        if: github.event_name == 'push' && github.ref == 'refs/heads/noetic'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and optionally push image
        uses: docker/build-push-action@v5
        with:
          context: Docker/base
          file: Docker/base/Dockerfile
          platforms: linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/noetic' }}
          tags: mcgillrobotics/auv_2025:base-arm64-temp

  build-and-push-base:
    name: base multi-arch Docker image
    runs-on: ubuntu-22.04
    needs:
      - build-and-push-base-amd64
      - build-and-push-base-arm64
    if: github.event_name == 'push' && github.ref == 'refs/heads/noetic'

    steps:
      - name: Free Disk Space
        uses: netbrain/free-disk-space-action@v0.0.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create multi-arch base image manifest
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: mcgillrobotics/auv_2025:base
          sources: |
            mcgillrobotics/auv_2025:base-amd64-temp
            mcgillrobotics/auv_2025:base-arm64-temp
          
  build-and-push-sim:
    name: sim multi-arch Docker image
    runs-on: ubuntu-22.04-arm
    needs:
      - build-and-push-base-amd64
      - build-and-push-base-arm64

    steps:
      - name: Free Disk Space
        uses: netbrain/free-disk-space-action@v0.0.1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (only if pushing)
        if: github.event_name == 'push' && github.ref == 'refs/heads/noetic'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and optionally push image
        uses: docker/build-push-action@v5
        with:
          context: Docker/sim
          file: Docker/sim/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/noetic' }}
          tags: mcgillrobotics/auv_2025:sim

  build-and-push-poolside:
    name: poolside multi-arch Docker image
    runs-on: ubuntu-22.04-arm
    needs: build-and-push-sim

    steps:
      - name: Free Disk Space
        uses: netbrain/free-disk-space-action@v0.0.1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (only if pushing)
        if: github.event_name == 'push' && github.ref == 'refs/heads/noetic'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and optionally push image
        uses: docker/build-push-action@v5
        with:
          context: Docker/poolside
          file: Docker/poolside/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/noetic' }}
          tags: mcgillrobotics/auv_2025:poolside
