name: Docker Build & Push for base and dependencies

on:
  push:
    branches: [noetic]
    paths:
      - 'Docker/base/**'
      - 'Docker/sim/**'
      - 'Docker/poolside/**'
  pull_request:
    branches: [noetic]
    paths:
      - 'Docker/base/**'
      - 'Docker/sim/**'
      - 'Docker/poolside/**'
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # 4 AM Montreal time

jobs:
  build-and-push-base:
    name: Build and optionally push base Docker image
    runs-on: ubuntu-22.04

    steps:
      - name: Free Disk Space
        run: |
          echo "Before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /usr/local/lib/android
          echo "After cleanup:"
          df -h

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (only if pushing)
        if: github.event_name == 'push' && github.ref == 'refs/heads/noetic'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and optionally push image
        uses: docker/build-push-action@v5
        with:
          context: Docker/base
          file: Docker/base/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/noetic' }}
          tags: mcgillrobotics/auv_2025:base
          
  build-and-push-sim:
    name: Build and optionally push sim Docker image
    runs-on: ubuntu-22.04-arm
    needs: build-and-push-base

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (only if pushing)
        if: github.event_name == 'push' && github.ref == 'refs/heads/noetic'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and optionally push image
        uses: docker/build-push-action@v5
        with:
          context: Docker/sim
          file: Docker/sim/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/noetic' }}
          tags: mcgillrobotics/auv_2025:sim

  build-and-push-poolside:
    name: Build and optionally push poolside Docker image
    runs-on: ubuntu-22.04-arm
    needs: build-and-push-sim

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (only if pushing)
        if: github.event_name == 'push' && github.ref == 'refs/heads/noetic'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and optionally push image
        uses: docker/build-push-action@v5
        with:
          context: Docker/poolside
          file: Docker/poolside/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/noetic' }}
          tags: mcgillrobotics/auv_2025:poolside
