name: Docker Compose Build 'ros1' on ARM

on:
  push:
    branches: [noetic]
  pull_request:
    branches: [noetic]
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # 4 AM Montreal time

jobs:
  docker-arm-ci:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y \
            docker-ce \
            docker-ce-cli \
            containerd.io \
            docker-buildx-plugin \
            docker-compose-plugin
      - name: Build Docker Compose file
        run: |
          cd Docker/ros1
          docker compose build
